In [ ]:
#Array Programming with Numpy

In [1]:
import numpy as np

In [2]:
a=np.arange(15)
b=np.arange(20)

In [3]:
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
print (a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

2
(3, 5)
15
int32
4
<class 'numpy.ndarray'>


In [6]:
sinchu = np.array([1.0,2.0,3.0,4.0])
print(sinchu)
print(sinchu.dtype)
print(type(sinchu))

[1. 2. 3. 4.]
float64
<class 'numpy.ndarray'>


In [7]:
sinchu = np.array([1,2,3,4])
print(sinchu.dtype)

int32


In [8]:
c=np.eye(10)
dtype=np.float64
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
c=np.eye(7)
dtype=np.int64
c

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [10]:
d=np.linspace(-4,2,15,endpoint=True)
d

array([-4.        , -3.57142857, -3.14285714, -2.71428571, -2.28571429,
       -1.85714286, -1.42857143, -1.        , -0.57142857, -0.14285714,
        0.28571429,  0.71428571,  1.14285714,  1.57142857,  2.        ])

In [11]:
d=np.logspace(-4,2,15,endpoint=True)
d

array([1.00000000e-04, 2.68269580e-04, 7.19685673e-04, 1.93069773e-03,
       5.17947468e-03, 1.38949549e-02, 3.72759372e-02, 1.00000000e-01,
       2.68269580e-01, 7.19685673e-01, 1.93069773e+00, 5.17947468e+00,
       1.38949549e+01, 3.72759372e+01, 1.00000000e+02])

In [12]:
f=np.fromfunction(lambda i,j: i== j, (3,3),dtype=float)
f

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [13]:
f=np.fromfunction(lambda i,j: i!= j, (3,3),dtype=float)
f

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [14]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a*2


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [16]:
a+a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [17]:
a*a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [18]:
print(a)
b=a.transpose()
b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [19]:
a@b

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [20]:
print(a)
a.sum(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [21]:
print(a)
a.sum(axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [22]:
a.sum()

66

In [23]:
print(a.min(),a.max())

0 11


In [24]:
sinchu = a*np.pi/12.0
print(sinchu)

[[0.         0.26179939 0.52359878 0.78539816]
 [1.04719755 1.30899694 1.57079633 1.83259571]
 [2.0943951  2.35619449 2.61799388 2.87979327]]


In [25]:
c=np.cos(sinchu)
c

array([[ 1.00000000e+00,  9.65925826e-01,  8.66025404e-01,
         7.07106781e-01],
       [ 5.00000000e-01,  2.58819045e-01,  6.12323400e-17,
        -2.58819045e-01],
       [-5.00000000e-01, -7.07106781e-01, -8.66025404e-01,
        -9.65925826e-01]])

In [26]:
k=np.sin(sinchu)
k


array([[0.        , 0.25881905, 0.5       , 0.70710678],
       [0.8660254 , 0.96592583, 1.        , 0.96592583],
       [0.8660254 , 0.70710678, 0.5       , 0.25881905]])

In [27]:
i = np.arange(100)
even= i[0:99:2]
print(even)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [28]:
sinchu = np.arange(100)
multiple = sinchu[5:100:5]
print(multiple)

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [29]:
a=np.arange(10)
a
        

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a[8]
        

8

In [31]:
print(a[2:5])

[2 3 4]


In [32]:
a[2:4]

array([2, 3])

In [33]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
a[2,1]

11

In [36]:
a[1:3,0:2]

array([[ 5,  6],
       [10, 11]])

In [37]:
a[:,1]

array([ 1,  6, 11])

In [38]:
a=a.flatten()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [39]:
for p in a:
    print(p)



0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [40]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [41]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
b=a
b is a

True

In [43]:
b.shape=(2,5)
print(b)
a.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [44]:
b is a

True

In [45]:
print(a)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [46]:
#shallow copy
a=np.arange(12)
c=a[:]
a.shape=(3,4)
print(a)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [47]:
d=c[3:8]
print(d)

[3 4 5 6 7]


In [48]:
d[:]=0


In [49]:
print(a)
print(b)
print(c)

[[ 0  1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 0  1  2  0  0  0  0  0  8  9 10 11]


In [50]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
False
True


In [51]:
#deep copy
d=a.copy()
d[:,:]=0.0
print(a)
print(d)

[[ 0  1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [52]:
#boolean indexing
import numpy as np
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a[a>4]=0   # numbers greater than 4 will be 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [54]:
a[a==0]=-1
a

array([[-1,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [55]:
a==-1  # if we use comparing operator it will return boolean values

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [60]:
print(a)
a[np.logical_and(a>3 , a<=9)]=7
a

[[-1  1  2  3]
 [ 0 -1 -1 -1]
 [-1 -1 -1 -1]]


array([[-1,  1,  2,  3],
       [ 0, -1, -1, -1],
       [-1, -1, -1, -1]])

In [59]:
a>4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [65]:
#avoiding loops concept

M=32
N=64

xmin = ymin = 0.0
xmax = ymax =1.0

x = np.linspace(xmin , xmax , M, endpoint=False)
y = np.linspace(ymin , ymax , N, endpoint=False)

print(x.shape)
print(y.shape)

print(x)
print(y)

(32,)
(64,)
[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     0.765625 0.78125  0.796875 0.8125   0.828125 0.84375  0.859375
 0.875    0.890625 0.90625  0.921875 0.9375   0.953125 0.96875  0.984375]


In [4]:
#time
import numpy as np
import time
M=32
N=64

x = np.linspace(0.0,1.0,M , endpoint  = False)
y = np.linspace(0.0,1.0,N , endpoint  = False)

x


array([0.     , 0.03125, 0.0625 , 0.09375, 0.125  , 0.15625, 0.1875 ,
       0.21875, 0.25   , 0.28125, 0.3125 , 0.34375, 0.375  , 0.40625,
       0.4375 , 0.46875, 0.5    , 0.53125, 0.5625 , 0.59375, 0.625  ,
       0.65625, 0.6875 , 0.71875, 0.75   , 0.78125, 0.8125 , 0.84375,
       0.875  , 0.90625, 0.9375 , 0.96875])

In [7]:
t0 = time.time()
g = np.zeros((M,N))
print(g)

for i in range(M):
    for j in range(N):
        g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])
        
        
print(g)
t1 = time.time()
print("time elapsed:{} s".format(t1-t0))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.00306796  0.00613588 ...  0.18605515  0.18906866
   0.1920804 ]
 [ 0.          0.00613588  0.01227154 ...  0.365613    0.37131719
   0.37700741]
 ...
 [ 0.          0.08885355  0.17700422 ... -0.75520138 -0.69397146
  -0.62725182]
 [ 0.          0.09190896  0.18303989 ... -0.62005721 -0.54532499
  -0.4659765 ]
 [ 0.          0.0949635   0.18906866 ... -0.46325978 -0.37700741
  -0.28734746]]
time elapsed:1.2844583988189697 s


In [10]:
x2d , y2d = np.meshgrid(x,y,indexing = "ij") // we can define more dan one variable in a single line

print(x2d)
print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])

[[0.      0.      0.      ... 0.      0.      0.     ]
 [0.03125 0.03125 0.03125 ... 0.03125 0.03125 0.03125]
 [0.0625  0.0625  0.0625  ... 0.0625  0.0625  0.0625 ]
 ...
 [0.90625 0.90625 0.90625 ... 0.90625 0.90625 0.90625]
 [0.9375  0.9375  0.9375  ... 0.9375  0.9375  0.9375 ]
 [0.96875 0.96875 0.96875 ... 0.96875 0.96875 0.96875]]
[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.

In [12]:
t0 = time.time()
g2 = np.sin(2.0*np.pi*x2d*y2d)

print(g2)

t1 = time.time()
print("time elapsed:{}s".format(t1-t0))

[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.00306796  0.00613588 ...  0.18605515  0.18906866
   0.1920804 ]
 [ 0.          0.00613588  0.01227154 ...  0.365613    0.37131719
   0.37700741]
 ...
 [ 0.          0.08885355  0.17700422 ... -0.75520138 -0.69397146
  -0.62725182]
 [ 0.          0.09190896  0.18303989 ... -0.62005721 -0.54532499
  -0.4659765 ]
 [ 0.          0.0949635   0.18906866 ... -0.46325978 -0.37700741
  -0.28734746]]
time elapsed:0.008626937866210938s


In [14]:
#array concatination
x = np.array([1,2,3,4])
y = np.array([4,5,6,7])

np.concatenate([y,x])

array([4, 5, 6, 7, 1, 2, 3, 4])

In [15]:
sinchu = np.array(['s','i','n','c','h'])
chinthu = np.array(['c','h','i'])

np.concatenate([chinthu,sinchu])

array(['c', 'h', 'i', 's', 'i', 'n', 'c', 'h'], dtype='<U1')

In [16]:
amma = np.array(['rekha'])
np.concatenate([amma,sinchu,chinthu])

array(['rekha', 's', 'i', 'n', 'c', 'h', 'c', 'h', 'i'], dtype='<U5')

In [21]:
addition = np.array([[10,20,30,40],
                    [90,50,60,70]])

np.concatenate([addition,addition])

array([[10, 20, 30, 40],
       [90, 50, 60, 70],
       [10, 20, 30, 40],
       [90, 50, 60, 70]])

In [23]:
addition = np.array([[10,20,30,40],
                    [90,50,60,70]])

np.concatenate([addition,addition] ,axis=1)  #along column

array([[10, 20, 30, 40, 10, 20, 30, 40],
       [90, 50, 60, 70, 90, 50, 60, 70]])

In [26]:
#splitting of array
x = [1,2,3,4,4,3,2,1,9,4,6]
x1,x2,x3 = np.split(x,[5,8])
print(x1,x2,x3)

[1 2 3 4 4] [3 2 1] [9 4 6]


In [27]:
doll = np.arange(25).reshape((5,5))
doll

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
left,right = np.split(doll ,[2])
print(left)
print(right)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [30]:
np.add.reduce(doll)

array([50, 55, 60, 65, 70])

In [31]:
x = np.arange(1,9)
print(x)
np.add.reduce(x)

[1 2 3 4 5 6 7 8]


36

In [32]:
np.multiply.reduce(x)

40320

In [33]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [34]:
np.multiply.accumulate(x)

array([    1,     2,     6,    24,   120,   720,  5040, 40320],
      dtype=int32)